global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # AvatarChatbot Backend Server (TGI)
  - job_name: 'avatarchatbot-backend-tgi'
    static_configs:
      - targets: ['avatarchatbot-backend-server:8888']

  # TGI Service (LLM)
  - job_name: 'avatarchatbot-tgi-service'
    static_configs:
      - targets: ['tgi-service:80']

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 
